/**
 * Liability, acknowledgement and provenance text.
 *
 * Single source for the About tab and the generated PDF report. The report is
 * the copy that leaves the building — a signed-off disclaimer that has drifted
 * from the one shown in the app is worse than no disclaimer at all, so both
 * render from here rather than each carrying its own wording.
 */

/** A sentence with one italicised span in the middle. */
export type EmphasisedParagraph = {
  before: string;
  emphasis: string;
  after: string;
};

export const DISCLAIMER_PARAGRAPHS: string[] = [
  'PCAST is provided for research, educational, and engineering evaluation purposes only. ' +
    'The results generated by this software are estimates based on the input data, assumptions, ' +
    'and analytical models used by the application. Users are responsible for verifying all ' +
    'inputs and interpreting results using appropriate engineering judgment.',
  'Neither the authors, developers, sponsoring organizations, nor their affiliated institutions ' +
    'make any warranty, expressed or implied, regarding the accuracy, completeness, reliability, ' +
    'or suitability of the software or its results for any particular purpose. The authors and ' +
    'affiliated organizations shall not be liable for any damages arising from the use of this ' +
    'application.',
  'The contents of this report reflect the views of the authors, who are responsible for the ' +
    'facts and accuracy of the information presented herein. The contents do not necessarily ' +
    'reflect the official views or policies of the Federal Highway Administration (FHWA) or the ' +
    'U.S. Department of Transportation. Mention of trade names, commercial products, or ' +
    'organizations does not constitute endorsement by the U.S. Government.'
];

/**
 * The About tab says "this website"; a printed report says "this report". Only
 * the third paragraph differs, so the on-screen variant is derived rather than
 * duplicated.
 */
export const DISCLAIMER_PARAGRAPHS_WEB: string[] = DISCLAIMER_PARAGRAPHS.map((p) =>
  p.replace('The contents of this report reflect', 'The contents of this website reflect')
);

export const ORIGINAL_WORK: EmphasisedParagraph = {
  before:
    'PCAST is based on a spreadsheet-based methodology developed under Cooperative Agreement ' +
    '693JJ31950004, ',
  emphasis: 'Advancing Concrete Pavement Technology Solutions',
  after:
    ', managed by the Concrete Pavement Technology Center (CP Tech Center) at Iowa State ' +
    'University and sponsored by the Federal Highway Administration (FHWA).'
};

export const ORIGINAL_CONTRIBUTORS: string[] = [
  'Armen Amirkhanian',
  'Lev Khazanovich',
  'Sushobhan Sen',
  'Alexander Brand',
  'Jeff Roesler',
  'Amanda Bordelon',
  'Shane Crawford',
  'Grace Vaughan'
];

export const WEBAPP_DEVELOPMENT =
  'The original spreadsheet methodology was converted into this SvelteKit-based web application ' +
  'by Maddie Lassiter and Armen Amirkhanian. The development of the web application served as ' +
  "the culminating project for Maddie Lassiter's Master's degree. Large language models from " +
  'both OpenAI and Anthropic were used for various parts of this project.';

export const FUNDING_ACKNOWLEDGMENT =
  'Development of the original methodology was supported through funding provided by the Federal ' +
  'Highway Administration (FHWA) under the Advancing Concrete Pavement Technology Solutions ' +
  'program administered by the Concrete Pavement Technology Center at Iowa State University.';

/** Data provenance, for the report's acknowledgement page. */
export const DATA_SOURCES: { label: string; value: string }[] = [
  {
    label: 'Climate normals',
    value:
      'NOAA U.S. Hourly Climate Normals, 1991–2020, transformed for this application ' +
      '(doi:10.57967/hf/8418).'
  },
  {
    label: 'Live forecast',
    value:
      'NOAA National Weather Service gridded forecast API (api.weather.gov). A forecast is a ' +
      'single predicted realisation and is valid only for the issuance time recorded with the ' +
      'analysis.'
  },
  {
    label: 'Source code',
    value: 'github.com/ArmenAmirkhanian/PCAST (AGPL-3.0-or-later).'
  }
];
