<div class="space-y-6 max-w-3xl">
  <section>
    <h2 class="text-xl font-semibold mb-2">About PCAST</h2>
    <p class="text-gray-700 leading-relaxed">
      The Pavement Cracking Analysis and Stress Tool (PCAST) is a web-based application
      for evaluating early-age thermal and shrinkage cracking in concrete pavements.
      The software models hydration-driven temperature development, environmental
      boundary conditions, and the resulting stress state within a pavement slab to
      estimate cracking potential during the curing period.
    </p>

    <p>
      The source code to this webapp can be found here: <a href="https://github.com/ArmenAmirkhanian/PCAST" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:underline">GitHub Repository</a>
    </p>

    <p>
      The 30-year climate normal dataset from NOAA, transformed to work with this webapp, can be found here: <a href="https://doi.org/10.57967/hf/8418" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:underline">10.57967/hf/8418</a>
    </p>

    <p>
      The source code used to perform the climate normal transformation can be found here: <a href="https://github.com/ArmenAmirkhanian/ClimateNormalsIngestor" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:underline">GitHub Repository</a>
    </p>
  </section>

  <section>
    <h2 class="text-xl font-semibold mb-2">Original Work</h2>
    <p class="text-gray-700 leading-relaxed mb-3">
      PCAST is based on a spreadsheet-based methodology developed under Cooperative
      Agreement 693JJ31950004, <em>Advancing Concrete Pavement Technology Solutions</em>,
      managed by the Concrete Pavement Technology Center (CP Tech Center) at Iowa State
      University and sponsored by the Federal Highway Administration (FHWA).
    </p>

    <p class="text-gray-700 mb-3">
      Original contributors include:
    </p>

    <ul class="list-disc list-inside space-y-1 text-gray-700">
      <li>Armen Amirkhanian</li>
      <li>Lev Khazanovich</li>
      <li>Sushobhan Sen</li>
      <li>Alexander Brand</li>
      <li>Jeff Roesler</li>
      <li>Amanda Bordelon</li>
      <li>Shane Crawford</li>
      <li>Grace Vaughan</li>
    </ul>
  </section>

  <section>
    <h2 class="text-xl font-semibold mb-2">Web Application Development</h2>
    <p class="text-gray-700 leading-relaxed">
      The original spreadsheet methodology was converted into this SvelteKit-based web
      application by Maddie Lassiter and Armen Amirkhanian. The development of the web
      application served as the culminating project for Maddie Lassiter's Master's degree. Large language models from both OpenAI and Anthropic were used for various parts of this project.
    </p>
  </section>

  <section>
    <h2 class="text-xl font-semibold mb-2">Funding Acknowledgment</h2>
    <p class="text-gray-700 leading-relaxed">
      Development of the original methodology was supported through funding provided by
      the Federal Highway Administration (FHWA) under the Advancing Concrete Pavement
      Technology Solutions program administered by the Concrete Pavement Technology Center
      at Iowa State University.
    </p>
  </section>

  <section>
    <h2 class="text-xl font-semibold mb-2">Disclaimer</h2>
    <p class="text-gray-700 leading-relaxed mb-3">
      PCAST is provided for research, educational, and engineering evaluation purposes
      only. The results generated by this software are estimates based on the input data,
      assumptions, and analytical models used by the application. Users are responsible
      for verifying all inputs and interpreting results using appropriate engineering
      judgment.
    </p>

    <p class="text-gray-700 leading-relaxed mb-3">
      Neither the authors, developers, sponsoring organizations, nor their affiliated
      institutions make any warranty, expressed or implied, regarding the accuracy,
      completeness, reliability, or suitability of the software or its results for any
      particular purpose. The authors and affiliated organizations shall not be liable
      for any damages arising from the use of this application.
    </p>

    <p class="text-gray-700 leading-relaxed">
      The contents of this website reflect the views of the authors, who are responsible
      for the facts and accuracy of the information presented herein. The contents do not
      necessarily reflect the official views or policies of the Federal Highway
      Administration (FHWA) or the U.S. Department of Transportation. Mention of trade
      names, commercial products, or organizations does not constitute endorsement by the
      U.S. Government.
    </p>
  </section>
</div>
